#@copyright : Ahmed Maged
CC=arm-none-eabi-
CFLAGS= -mcpu=cortex-m3
INCS=-I .
LIBS=
SRC =$(wildcard *.c)
OBJ =$(SRC:.c=.o)
As = $(wildcard *.s)
AsOBJ=$(As:.s=.o)
project_name = learn_in_depth_lab2

all: $(project_name).bin
	@echo "========Build is Done ========"

	
%.o:%.c
	$(CC)gcc.exe -mthumb -c $(CFLAGS) $(INCS) $< -o $@
	
$(project_name).elf:$(OBJ) $(AsOBJ)
	$(CC)ld.exe -T Linker_Script.ld $(LIBS) $(OBJ) $(AsOBJ) -o $@ -Map=Map_file.map
	
$(project_name).bin:$(project_name).elf
	$(CC)objcopy.exe -O binary $< $@
	
clean_all:
	rm *.o *.elf *.bin
	@echo "Everything clean successfully"
	
clean:
	rm *.elf *.bin