#@copyright : Ahmed Maged
CC=arm-none-eabi-
CFLAGS= -mcpu=cortex-m4 -gdwarf-2 -g
INCS=-I .
LIBS=
SRC =$(wildcard *.c)
OBJ =$(SRC:.c=.o)
As = $(wildcard *.s)
AsOBJ=$(As:.s=.o)
project_name = learn_in_depth_lab4

all: $(project_name).bin
	@echo "========Build is Done ========"
	
%.o:%.s
	$(CC)as.exe $(CFLAGS) $< -o $@
	
%.o:%.c
	$(CC)gcc.exe -mthumb -c $(CFLAGS) $(INCS) $< -o $@
	
$(project_name).elf:$(OBJ) $(AsOBJ)
	$(CC)ld.exe -T Linker_Script.ld $(LIBS) $(OBJ) $(AsOBJ) -o $@ -Map=Map_file.map
	cp $(project_name).elf $(project_name).axf
$(project_name).bin:$(project_name).elf
	$(CC)objcopy.exe -O binary $< $@
	
clean_all:
	rm *.o *.elf *.bin
	@echo "Everything clean successfully"
	
clean:
	rm *.elf *.bin